### ISSUE TITLE
dplyr::collect

### ISSUE THREAD

**Issue by lorenzwalthert** [mdsumner/lazysf#2]
I saw from the docs that you have `st_as_sf()`,  but I wonder if using `collect()` wouldn't feel more natural for most dplyr users. Maybe this could be implemented as an S3 generic.

**Comment by mdsumner** [comment]
It already works, I don't think I had to do anything. Does it not for you?

You need 'st_as_sf' to class the dataframe and do the method for that runs 'collect()' first

**Comment by lorenzwalthert** [comment]
I did not try it before filing the issue 😜. Indeed it works and adding to the docs sounds great. But `collect()` does not give an sf object but a tibble with a geometry column. Maybe that was intentional but I would have hoped it to be an sf object already. But it's a detail, I can just use `st_as_sf()` in the first place. No idea if it's a convention that `dplyr::collect()` always returns a tibble. You can close at your desire.

**Comment by mdsumner** [comment]
Ok cool - it's still an open topic for me so I'll keep it open in case others comment or I figure out something else! 

I like that `collect()` is just a data frame (a tibble that is). 

If `collect()` returned an sf then I think it's strange when there's no geometry column and we get a data frame in that case, and if I wanted a data frame then I'm undoing the step to `st_as_sf()`. 

I might change my mind as this package is *actually using sf* rather than treating it as a possible output format.

**Comment by lorenzwalthert** [comment]
I see. I think above all it’s important that there is type stability in the output class, also with tibble and data.frame because there are subtle differences.

**Comment by mdsumner** [comment]
I think as-is now it gives type-stability, yes? 

One wrinkle is that `sf::st_as_sf()` is no good as a delay-breaker if there isn't a geometry column, but `as.data.frame()` and `as_tibble()` both work in place of `collect()`.  But that's a pro in terms of type-stable. 

I'm not sure if I'm missing anything, but at the least I'll document those and link them together. I think I'll write about this in more detail and ask around a bit.

**Comment by lorenzwalthert** [comment]
Great. Yes, I think there is type stability, but you would loose if you would return a tibble f there was no geometry column and an sf object otherwise.

**Comment by mdsumner** [comment]
I'm happy with the setup now.
